"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import type {Answer,ConnectionStatus,Episode,KnowledgeItem,PlaybackRate} from "../lib/podcast";
import {choosePlaybackRate,filterKnowledgeItems,playbackRates,stages} from "../lib/podcast";
import {QuestionAnswerPlayer,QuestionHistory,VoiceQuestionButton,submitQuestion,type Question} from "./voice-question";
type View="discover"|"create"|"library"|"episode";
type Saved=Pick<Episode,"id"|"title"|"status"|"stage"|"createdAt"|"minutes"> & {author?:string;duration:number};
const time=(s:number)=>`${Math.floor((s||0)/60).toString().padStart(2,"0")}:${Math.floor((s||0)%60).toString().padStart(2,"0")}`;
async function api<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,init);let d;try{d=await r.json();}catch{throw new Error("服务暂时没有响应，请稍后再试。");}if(!r.ok)throw new Error(d.error||"请求没有完成，请重试。");return d;}
const post=(body:unknown={},extra:Record<string,string>={})=>({method:"POST",headers:{"Content-Type":"application/json",...extra},body:JSON.stringify(body)});
function Mark(){return <span className="sound-mark" aria-hidden="true"><i/><i/><i/><i/></span>;}
function Play({paused=false}:{paused?:boolean}){return <span aria-hidden="true" className={paused?"pause-symbol":"play-symbol"}/>;}
function Wave({active=false}:{active?:boolean}){return <div className={`wave ${active?"active":""}`} aria-hidden="true">{Array.from({length:25},(_,i)=><i key={i} style={{height:`${10+Math.abs(Math.sin(i*1.91))*36}px`,animationDelay:`${i*.055}s`}}/>)}</div>;}
export default function Home(){
  const [view,setView]=useState<View>("discover"),[items,setItems]=useState<KnowledgeItem[]>([]),[loading,setLoading]=useState(true),[listError,setListError]=useState("");
  const [query,setQuery]=useState(""),[status,setStatus]=useState<ConnectionStatus|null>(null),[saved,setSaved]=useState<Saved[]>([]),[savedError,setSavedError]=useState("");
  const [selected,setSelected]=useState<KnowledgeItem|null>(null),[source,setSource]=useState<Answer|null>(null),[sourceLoading,setSourceLoading]=useState(false),[minutes,setMinutes]=useState<3|8>(3);
  const [ep,setEp]=useState<Episode|null>(null),[running,setRunning]=useState(false),[creating,setCreating]=useState(false),[error,setError]=useState("");
  const [settings,setSettings]=useState(false),[sourceOpen,setSourceOpen]=useState(false),[sourceFocus,setSourceFocus]=useState<string[]>([]),[tab,setTab]=useState<"chapters"|"transcript"|"questions">("chapters");
  const [pos,setPos]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState<PlaybackRate>(1),[speedMenu,setSpeedMenu]=useState(false),[toast,setToast]=useState("");
  const [questionBusy,setQuestionBusy]=useState(false),[questionRefresh,setQuestionRefresh]=useState(0),[answerQuestion,setAnswerQuestion]=useState<Question|null>(null);
  const audio=useRef<HTMLAudioElement|null>(null),speedControl=useRef<HTMLDivElement|null>(null),serial=useRef(0),key=useRef<string|null>(null);
  const loadList=async()=>{setLoading(true);setListError("");try{setItems((await api<{items:KnowledgeItem[]}>("/api/knowledge")).items);}catch(e){setListError((e as Error).message);}finally{setLoading(false);}};
  const loadStatus=async()=>{try{setStatus(await api<ConnectionStatus>("/api/status"));}catch{setStatus(null);}};
  const loadSaved=async()=>{setSavedError("");try{setSaved((await api<{episodes:Saved[]}>("/api/episodes")).episodes);}catch(e){setSavedError((e as Error).message);}};
  const navigate=(v:View)=>{setView(v);setError("");window.history.pushState({},"",v==="episode"&&ep?`/?episode=${ep.id}`:"/");};
  const openEpisode=async(id:string)=>{setError("");setRunning(false);try{const next=await api<Episode>(`/api/episodes/${id}`);setEp(next);setView("episode");setPos(0);window.history.pushState({},"",`/?episode=${id}`);}catch(e){setError((e as Error).message);}};
  useEffect(()=>{void loadList();void loadStatus();void loadSaved();const id=new URLSearchParams(window.location.search).get("episode");if(id)void openEpisode(id);const pop=()=>{setRunning(false);setView("discover");};window.addEventListener("popstate",pop);return()=>window.removeEventListener("popstate",pop);},[]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2600);return()=>clearTimeout(t);},[toast]);
  useEffect(()=>{
    if(!running||!ep||(ep.stage==="synthesizing"&&!status?.audioReady)||ep.status==="ready"||ep.status==="failed")return;
    let cancelled=false;const t=setTimeout(async()=>{try{const next=await api<Episode>(`/api/episodes/${ep.id}/advance`,post());if(!cancelled){setEp(next);if(next.status==="ready"||next.status==="failed"||(next.stage==="synthesizing"&&!status?.audioReady)){setRunning(false);void loadSaved();}}}catch(e){if(!cancelled){setError((e as Error).message);setRunning(false);}}},750);
    return()=>{cancelled=true;clearTimeout(t);};
  },[running,ep,status]);
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==="Escape"){setSettings(false);setSourceOpen(false);setSpeedMenu(false);}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler);},[]);
  useEffect(()=>{if(!speedMenu)return;const close=(e:PointerEvent)=>{if(!speedControl.current?.contains(e.target as Node))setSpeedMenu(false);};document.addEventListener("pointerdown",close);return()=>document.removeEventListener("pointerdown",close);},[speedMenu]);
  const pick=async(item:KnowledgeItem)=>{const n=++serial.current;setSelected(item);setSource(null);setSourceLoading(true);key.current=null;navigate("create");try{const s=await api<Answer>(`/api/knowledge/${item.id}`);if(n===serial.current)setSource(s);}catch(e){if(n===serial.current)setError((e as Error).message);}finally{if(n===serial.current)setSourceLoading(false);}};
  const create=async()=>{if(!selected||!source||creating)return;setCreating(true);setError("");key.current??=crypto.randomUUID();try{const next=await api<Episode>("/api/episodes",post({answerId:selected.id,minutes},{"Idempotency-Key":key.current}));setEp(next);setView("episode");setPos(0);window.history.pushState({},"",`/?episode=${next.id}`);setRunning(true);void loadSaved();}catch(e){setError((e as Error).message);}finally{setCreating(false);}};
  const retry=async()=>{if(!ep||creating)return;setError("");setCreating(true);try{const next=await api<Episode>(`/api/episodes/${ep.id}/retry`,post());setEp(next);setRunning(next.status!=="ready"&&next.status!=="failed");}catch(e){setError((e as Error).message);}finally{setCreating(false);}};
  const currentSource=ep&&view==="episode"?ep.source:source;
  const showSource=(ids:string[]=[])=>{setSourceFocus(ids);setSourceOpen(true);};
  const duration=ep?.segments.reduce((n,s)=>n+(s.duration||0),0)||0;
  let offset=0;const timeline=ep?.segments.map(s=>{const t={...s,start:offset};offset+=s.duration||0;return t;})||[];
  const active=timeline.find(s=>pos>=s.start&&pos<s.start+(s.duration||0))||timeline[0];
  const chapters=timeline.filter((s,i)=>i===0||timeline[i-1].chapter!==s.chapter);
  const seek=(v:number)=>{if(audio.current){audio.current.currentTime=Math.max(0,Math.min(duration,v));setPos(audio.current.currentTime);}};
  const play=async()=>{if(!audio.current)return;try{if(audio.current.paused)await audio.current.play();else audio.current.pause();}catch{setError("音频暂时无法播放，请再次点击或刷新重试。");}};
  const selectSpeed=(selected:PlaybackRate)=>{setSpeed(choosePlaybackRate(audio.current,selected));setSpeedMenu(false);};
  const pauseAll=useCallback(()=>{audio.current?.pause();setAnswerQuestion(null);},[]);
  const askQuestion=useCallback(async(blob:Blob,position:number)=>{if(!ep)return;setQuestionBusy(true);setError("");try{const q=await submitQuestion(ep.id,blob,position) as Question;setAnswerQuestion(q);setQuestionRefresh(x=>x+1);setTab("questions");}catch(e){setError((e as Error).message);}finally{setQuestionBusy(false);}},[ep]);
  const playAnswer=useCallback((q:Question)=>{audio.current?.pause();setAnswerQuestion(q);},[]);
  const share=async()=>{if(!ep)return;const url=`${window.location.origin}/?episode=${ep.id}`;try{if(navigator.share)await navigator.share({title:ep.title,url});else{await navigator.clipboard.writeText(url);setToast("节目链接已复制");}}catch{setToast("可复制浏览器地址分享这期节目");}};
  const keyword=query.trim(),filtered=filterKnowledgeItems(items,query);
  const ready=view==="episode"&&ep?.status==="ready";
  return <div className="site-frame">
    <aside className="desktop-note"><a className="wordmark" href="/" onClick={e=>{e.preventDefault();navigate("discover");}}><Mark/>听见<small>TINGJIAN</small></a><h1>每一个好回答，<br/>都值得被听见。</h1><p>把知乎的一篇优质内容，<br/>变成一场属于你的双人播客。</p><div className="desktop-rule"/><span className="eyebrow">READ LESS. LISTEN CLOSER.</span><div className="desktop-bottom">移动端体验 · 手机打开链接即可收听</div></aside>
    <main className={`phone-app ${ready?"player-mode":""}`}>
      <header className="app-header">{view==="discover"||view==="library"?<a className="wordmark" href="/" onClick={e=>{e.preventDefault();navigate("discover");}}><Mark/>听见<small>好回答，新声音</small></a>:<button className="back-button" onClick={()=>navigate("discover")} aria-label="返回发现页">‹<span>{view==="create"?"制作播客":"我的节目"}</span></button>}<button className="icon-button" onClick={()=>setSettings(true)} aria-label="查看服务状态">⋯</button></header>
      {error&&<div className="notice error" role="alert">{error}<button onClick={()=>setError("")} aria-label="关闭提示">×</button></div>}
      {view==="discover"&&<>
        <section className="home-hero"><div className="eyebrow"><span className="live-dot"/>FROM ANSWER TO AUDIO</div><h1>把好回答，<br/>听成一场<span>对谈。</span></h1><p>一个观点，两种声音。<br/>让值得读的内容，陪你走一段路。</p><div className="hero-art" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><div className="record"><span className="record-label"><Mark/><small>TINGJIAN<br/>SIDE A</small></span></div><div className="art-sticker">给耳朵<br/>一点好内容</div></div><button className="primary hero-cta" onClick={()=>{document.getElementById("content-list")?.scrollIntoView({behavior:"smooth"});document.getElementById("search")?.focus({preventScroll:true});}}><span>选一篇，开始听</span><span>↗</span></button><div className="hero-foot"><span>知乎知识内容</span><span>AI 双人解读</span><span>原文可对照</span></div></section>
        <section className="discover-section" id="content-list"><div className="section-heading"><div><div className="eyebrow">THE READING ROOM</div><h2>从一篇好内容开始</h2></div><span className="small-pill">{keyword?`找到 ${filtered.length} 篇`:items.length?`${items.length} 篇可选`:"知乎内容"}</span></div><label className="search-box"><span aria-hidden="true">⌕</span><input id="search" placeholder="筛选这 10 篇知乎知识内容" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="清除筛选" onClick={()=>setQuery("")}>×</button>}</label><p className="search-scope">内容来自知乎黑客松精选知识库，并非知乎全站搜索</p>
        {loading&&<div className="empty loading-text"><span className="loading-dot"/>正在取回知乎的好内容</div>}{listError&&<div className="empty"><p>{listError}</p><button className="text-button" onClick={loadList}>重新加载 ↻</button></div>}{!loading&&!listError&&keyword&&!filtered.length&&<div className="empty filter-empty"><strong>当前 10 篇精选内容中没有“{keyword}”</strong><p>换个关键词，或浏览下方全部内容。</p><button className="secondary" onClick={()=>setQuery("")}>清除筛选，查看全部</button></div>}
        <div className="content-list">{filtered.map((item,i)=><button className="content-item" key={item.id} onClick={()=>pick(item)}><div className={`cover-mini palette-${i%4}`} aria-hidden="true"><span>{String(i+1).padStart(2,"0")}</span><div className="cover-lines"/><small>好内容<br/>值得听</small></div><div className="item-copy"><span className="item-kicker">知乎知识 · 可制作播客</span><h3>{item.title}</h3><p>{item.description}</p><span className="item-action">读一下，再制作 <span>↗</span></span></div></button>)}</div></section><div className="bottom-caption"><Mark/><span>把阅读留给眼睛，把思考交给声音。</span></div>
      </>}
      {view==="create"&&<div className="create-page"><div className="eyebrow">YOUR LITTLE AUDIO STUDIO</div><h1>把这一篇，<br/>变成你的播客。</h1>{!selected?<div className="empty"><p>先选一篇你想听的内容</p><button className="primary" onClick={()=>navigate("discover")}>去挑一篇 ↗</button></div>:<>
        <div className="source-preview"><div className="source-meta"><span className="zhihu-letter">知</span>知乎知识内容<span className="meta-right">原文素材</span></div><h2>{selected.title}</h2><p className="author-line">{sourceLoading?"正在读取作者与正文…":source?`${source.author} · ${source.paragraphs.reduce((n,p)=>n+p.text.length,0).toLocaleString()} 字`:"正文尚未读取"}</p><p className="source-excerpt">{source?.paragraphs.slice(0,2).map(p=>p.text).join(" ")||selected.description}</p>{source&&<button className="text-button" onClick={()=>showSource()}>查看完整素材 ↗</button>}{!sourceLoading&&!source&&<button className="text-button" onClick={()=>pick(selected)}>重新读取正文 ↻</button>}</div>
        {source?.incomplete&&<div className="notice">接口正文的结尾可能不完整。节目仅依据已返回内容制作。</div>}
        <h3 className="field-title">这次，想听多久？</h3><div className="mode-options">{([3,8] as const).map(m=><button key={m} className={`mode-option ${minutes===m?"selected":""}`} onClick={()=>{setMinutes(m);key.current=null;}}><span className="mode-check"/><strong>约 {m} 分钟</strong><b>{m===3?"轻轻听懂":"慢慢聊透"}</b><small>{m===3?"观点与关键理由":"观点、案例与适用边界"}</small></button>)}</div>
        <h3 className="field-title">今天，由他们来聊</h3><div className="hosts-row"><div className="avatar peach">问</div><div><strong>好奇的主持人</strong><small>替你追问，串起思路</small></div><span className="host-plus">＋</span><div className="avatar sage">说</div><div><strong>耐心的讲述人</strong><small>循着原文，娓娓道来</small></div></div>
        <div className="generate-footer">{!status?.ready&&<div className="connection-note"><span className="amber-dot"/><span>{status?.textReady?"可先生成文字稿，语音稍后接入":status?"AI 编导待配置":"正在检查生成服务"}</span><button onClick={()=>setSettings(true)}>查看</button></div>}<button className="primary generate-button" disabled={!source||!status?.textReady||creating} onClick={create}><Mark/><span>{creating?"正在创建节目…":status?.audioReady?"生成我的播客":"生成播客文字稿"}</span><span>↗</span></button></div>
      </>}</div>}
      {view==="episode"&&ep&&ep.status!=="ready"&&<div className="generation-page"><div className="eyebrow">A GOOD ANSWER IS FINDING ITS VOICE</div><h1>{ep.review?.passed&&ep.stage==="synthesizing"&&!status?.audioReady?"播客文字稿已准备好":ep.status==="failed"?"稍等一下，\n我们需要重试。":running?"好内容，\n正在变成好声音。":"这期节目，\n等你继续制作。"}</h1><div className={`generation-disc ${running?"turning":""}`}><Mark/></div><h2>{ep.title}</h2><p className="muted">{ep.source?.author&&`${ep.source.author} · `}双人对谈 · 目标约 {ep.minutes} 分钟</p><div className="steps">{stages.slice(0,5).map((step,i)=>{const current=stages.findIndex(s=>s.id===ep.stage);return <div className={`step ${i<current?"done":i===current?"current":""}`} key={step.id}><span className="step-number">{i<current?"✓":String(i+1).padStart(2,"0")}</span><div><strong>{step.label}</strong><p>{step.id==="synthesizing"&&current===4?`${ep.completedAudio} / ${ep.segments.length} 段声音已保存`:step.detail}</p></div>{i===current&&running&&<span className="loading-dot"/>}</div>;})}</div>
        {ep.error&&<div className="notice error" role="alert">{ep.error}</div>}{!!ep.review?.issues.length&&<details className="review-details"><summary>查看需要修订的内容</summary>{ep.review.issues.map((issue,i)=><p key={i}>{issue}</p>)}</details>}
        {ep.status==="failed"?<button className="primary" disabled={creating} onClick={retry}>{creating?"正在重试…":"从当前阶段重试 ↻"}</button>:<button className={running?"secondary":"primary"} disabled={ep.stage==="synthesizing"&&!status?.audioReady} onClick={()=>setRunning(!running)}>{ep.stage==="synthesizing"&&!status?.audioReady?"接入语音后可继续合成":running?"暂停后续制作":"继续生成节目"}</button>}
        {ep.review?.passed&&ep.segments.length>0&&<section className="transcript"><h2>双人播客文字稿</h2><p className="muted">已通过 AI 原文核对 · 可逐段查看来源</p>{ep.segments.map(s=><div key={s.id} className="transcript-line"><strong>{s.speaker==="host"?"主持人":"讲述人"} · {s.chapter}</strong><p>{s.text}</p>{s.sourceIds.length>0&&<button className="citation" onClick={()=>showSource(s.sourceIds)}>查看原文依据 ↗</button>}</div>)}</section>}
        <p className="generation-help">制作时请保持页面打开。每完成一步都会保存进度，离开后可在「我的收听」继续。</p></div>}
      {ready&&ep&&<div className="player-page"><div className="player-topline"><span className="small-pill">单篇深读 · AI 对谈</span><button className="text-button" onClick={share}>分享 ↗</button></div><div className={`episode-art ${playing?"is-playing":""}`}><span className="art-eyebrow">TINGJIAN · ORIGINAL PERSPECTIVES</span><div className="episode-art-title">听见<br/><span>答案之外</span><i>THE CONVERSATION</i></div><div className="episode-art-record"><div><Mark/></div></div><Wave active={playing}/><span className="art-footer">一篇内容 / 两种声音 / 一次新理解</span></div><h1>{ep.title}</h1><p className="player-author">依据 {ep.source?.author} 的知乎内容改编</p><div className="speaker-pills"><span className={active?.speaker==="host"?"speaking":""}><i className="peach"/>主持人</span><span className={active?.speaker==="guest"?"speaking":""}><i className="sage"/>讲述人</span><small>AI 合成声音</small></div>
        <audio key={ep.id} ref={audio} src={`/api/episodes/${ep.id}/audio`} preload="metadata" onTimeUpdate={()=>setPos(audio.current?.currentTime||0)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onError={()=>setError("音频暂时无法加载，请检查网络后刷新重试。")} onLoadedMetadata={()=>{if(audio.current)audio.current.playbackRate=speed;}}/>
        <div className="seek-row"><input aria-label="播放进度" type="range" min={0} max={duration||1} step={.1} value={Math.min(pos,duration)} onChange={e=>seek(Number(e.target.value))} style={{"--progress":`${duration?pos/duration*100:0}%`} as React.CSSProperties}/><div><span>{time(pos)}</span><span>{time(duration)}</span></div></div><div className="play-controls"><div className="speed-control" ref={speedControl}><button className="speed-button" onClick={()=>setSpeedMenu(open=>!open)} aria-label={`播放速度 ${speed} 倍，点击选择`} aria-haspopup="menu" aria-expanded={speedMenu}>{speed}×</button>{speedMenu&&<div className="speed-menu" role="menu" aria-label="选择播放速度">{playbackRates.map(rate=><button key={rate} role="menuitemradio" aria-checked={speed===rate} className={speed===rate?"active":""} onClick={()=>selectSpeed(rate)}>{rate}×</button>)}</div>}</div><button className="skip-button" onClick={()=>seek(pos-15)} aria-label="后退15秒">↶<small>15</small></button><button className="big-play" aria-label={playing?"暂停":"播放"} onClick={()=>{setAnswerQuestion(null);void play();}}><Play paused={playing}/></button><button className="skip-button" onClick={()=>seek(pos+15)} aria-label="前进15秒">↷<small>15</small></button><button className="source-icon" onClick={()=>showSource(active?.sourceIds||[])}>原文</button></div>
        <VoiceQuestionButton onSubmit={askQuestion} position={pos} onPause={pauseAll} busy={questionBusy}/><QuestionAnswerPlayer question={answerQuestion} onDone={()=>setAnswerQuestion(null)} onError={setError}/>
        <div className="player-tabs" role="tablist"><button role="tab" aria-selected={tab==="chapters"} className={tab==="chapters"?"active":""} onClick={()=>setTab("chapters")}>节目章节</button><button role="tab" aria-selected={tab==="transcript"} className={tab==="transcript"?"active":""} onClick={()=>setTab("transcript")}>对话文字稿</button><button role="tab" aria-selected={tab==="questions"} className={tab==="questions"?"active":""} onClick={()=>setTab("questions")}>我的提问</button></div>
        {tab==="chapters"?<div className="chapters">{chapters.map((c,i)=><button key={c.id} className={active?.chapter===c.chapter?"active":""} onClick={()=>seek(c.start)}><span>{String(i+1).padStart(2,"0")}</span><strong>{c.chapter}</strong><small>{time(c.start)}</small><span>↗</span></button>)}</div>:tab==="transcript"?<div className="transcript">{timeline.map(s=><div key={s.id} className={`transcript-line ${active?.id===s.id?"active":""}`}><button className="transcript-jump" onClick={()=>seek(s.start)}><span>{s.speaker==="host"?"主持人":"讲述人"}</span><small>{time(s.start)}</small></button><p>{s.text}</p>{s.sourceIds.length>0?<button className="citation" onClick={()=>showSource(s.sourceIds)}>查看 {s.sourceIds.length} 处原文 ↗</button>:<small className="muted">节目串联语</small>}</div>)}</div>:<QuestionHistory episodeId={ep.id} refresh={questionRefresh} onSeek={p=>{pauseAll();seek(p);}} onPlayAnswer={playAnswer} onShowSource={showSource}/>} 
      </div>}
      {view==="library"&&<div className="library-page"><div className="eyebrow">YOUR PERSONAL SOUND SHELF</div><h1>慢慢积累，<br/>自己的声音书架。</h1><div className="library-summary"><strong>{saved.filter(e=>e.status==="ready").length}<small>期已生成</small></strong><strong>{Math.round(saved.filter(e=>e.status==="ready").reduce((n,e)=>n+e.duration,0)/60)}<small>分钟好内容</small></strong><button className="text-button" onClick={loadSaved}>刷新 ↻</button></div>{savedError&&<div className="notice error">{savedError}</div>}{!saved.length&&!savedError?<div className="empty-library"><div className="empty-record"><Mark/></div><h2>第一期，从好奇开始。</h2><p>选一篇感兴趣的知乎内容，<br/>把它放进你的耳机里。</p><button className="primary" onClick={()=>navigate("discover")}>去发现好内容 ↗</button></div>:saved.map(e=><button className="history-card" key={e.id} onClick={()=>openEpisode(e.id)}><div className="history-icon">{e.status==="ready"?<Play/>:<Mark/>}</div><div><span className={`status-label ${e.status==="failed"?"failed":""}`}>{e.status==="ready"?`${time(e.duration)} · 可收听`:e.status==="failed"?"制作中断 · 可重试":"制作中 · 可继续"}</span><h3>{e.title}</h3><small>{e.author||"知乎知识"} · {new Date(e.createdAt).toLocaleDateString("zh-CN",{month:"numeric",day:"numeric"})}</small></div><span>›</span></button>)}</div>}
      <nav className="bottom-nav" aria-label="主导航"><button className={view==="discover"?"active":""} onClick={()=>navigate("discover")}><span className="nav-discover"/>发现</button><button className={`nav-create ${view==="create"?"active":""}`} onClick={()=>navigate("create")}><span>＋</span>制作播客</button><button className={view==="library"?"active":""} onClick={()=>{navigate("library");void loadSaved();}}><span className="nav-library"/>我的收听</button></nav>
    </main>
    {settings&&<div className="modal-overlay" onClick={()=>setSettings(false)}><section role="dialog" aria-modal="true" aria-labelledby="status-title" className="bottom-sheet" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><button className="sheet-close" onClick={()=>setSettings(false)} aria-label="关闭">×</button><div className="eyebrow">STUDIO CONNECTIONS</div><h2 id="status-title">声音背后的连接</h2><p className="muted">真实获取内容、生成脚本，再合成声音。</p>{status?status.services.map(s=><div className="service-row" key={s.name}><span className={s.configured?"live-dot":"amber-dot"}/><div><strong>{s.name}</strong><small>{s.detail}</small></div><span className={`service-state ${s.configured?"ok":""}`}>{s.configured?"已配置":"待接入"}</span></div>):<div className="notice">暂时无法读取服务状态，请重试。</div>}<p className="connection-help">「已配置」表示接入参数已就绪，实际可用性以生成结果为准。缺少 AI 或语音配置时，仍可阅读知乎素材。</p><button className="secondary" onClick={loadStatus}>刷新状态 ↻</button></section></div>}
    {sourceOpen&&currentSource&&<div className="modal-overlay" onClick={()=>setSourceOpen(false)}><section role="dialog" aria-modal="true" aria-labelledby="source-title" className="bottom-sheet source-sheet" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><button className="sheet-close" onClick={()=>setSourceOpen(false)} aria-label="关闭原文">×</button><div className="eyebrow">BACK TO THE SOURCE</div><h2 id="source-title">{currentSource.title}</h2><p className="muted">{currentSource.author} · 知乎知识内容</p>{currentSource.incomplete&&<div className="notice">素材结尾可能不完整，以下展示接口实际返回的全部正文。</div>}<div className="source-paragraphs">{currentSource.paragraphs.map(p=><p key={p.id} className={sourceFocus.includes(p.id)?"highlight":""}><small>{p.id}</small>{p.text}</p>)}</div><a className="text-button" href={currentSource.url} target="_blank" rel="noopener noreferrer">查看知乎接口来源 ↗</a></section></div>}
    {toast&&<div role="status" className="toast">{toast}</div>}
  </div>;
}
