"use client";
import {useCallback,useEffect,useRef,useState} from "react";

export type Question = {id:string;positionSeconds:number;questionText:string;answerText?:string|null;sourceIds?:string[];status:string;errorCode?:string|null;createdAt:string;updatedAt?:string};
const anonymousId=()=>{const key="tingjian-anonymous-id";let id=localStorage.getItem(key);if(!id){id=crypto.randomUUID();localStorage.setItem(key,id);}return id;};
const anonymousHeaders=()=>({"X-Anonymous-Id":anonymousId()});

function encodeWav(samples:Float32Array,sampleRate:number){const bytes=new ArrayBuffer(44+samples.length*2),v=new DataView(bytes);const w=(o:number,s:string)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i));};w(0,"RIFF");v.setUint32(4,36+samples.length*2,true);w(8,"WAVE");w(12,"fmt ");v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,sampleRate,true);v.setUint32(28,sampleRate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);w(36,"data");v.setUint32(40,samples.length*2,true);for(let i=0;i<samples.length;i++){const s=Math.max(-1,Math.min(1,samples[i]));v.setInt16(44+i*2,s<0?s*0x8000:s*0x7fff,true);}return new Blob([bytes],{type:"audio/wav"});}

export function useVoiceQuestionRecorder(onComplete:(blob:Blob)=>void){const [state,setState]=useState<"idle"|"recording"|"error">("idle"),[seconds,setSeconds]=useState(0),[error,setError]=useState("");const ctx=useRef<AudioContext|null>(null);const stream=useRef<MediaStream|null>(null);const proc=useRef<ScriptProcessorNode|null>(null);const chunks=useRef<Float32Array[]>([]);const started=useRef(0);const timer=useRef<number|undefined>(undefined);const recording=useRef(false),pending=useRef(false),cancelPending=useRef(false);
 const stop=useCallback((submit=true)=>{if(pending.current){cancelPending.current=true;return;}if(!recording.current)return;recording.current=false;if(timer.current)window.clearInterval(timer.current);proc.current?.disconnect();stream.current?.getTracks().forEach(t=>t.stop());const c=ctx.current;c?.close();setState("idle");const all=chunks.current;chunks.current=[];if(submit&&all.length){const n=all.reduce((a,b)=>a+b.length,0),joined=new Float32Array(n);let o=0;all.forEach(x=>{joined.set(x,o);o+=x.length});const sr=c?.sampleRate||44100,ratio=sr/16000,out=new Float32Array(Math.floor(joined.length/ratio));for(let i=0;i<out.length;i++)out[i]=joined[Math.floor(i*ratio)];if(out.length>=4000)onComplete(encodeWav(out,16000));else setError("录音太短，请按住按钮说完问题后再松开。");}setSeconds(0);},[onComplete]);
 const start=useCallback(async()=>{if(recording.current||pending.current)return;pending.current=true;cancelPending.current=false;setError("");try{const s=await navigator.mediaDevices.getUserMedia({audio:true});if(cancelPending.current){s.getTracks().forEach(t=>t.stop());return;}stream.current=s;const c=new AudioContext();ctx.current=c;await c.resume();const src=c.createMediaStreamSource(s),p=c.createScriptProcessor(4096,1,1);proc.current=p;p.onaudioprocess=e=>chunks.current.push(new Float32Array(e.inputBuffer.getChannelData(0)));src.connect(p);p.connect(c.destination);started.current=Date.now();recording.current=true;setState("recording");setSeconds(0);timer.current=window.setInterval(()=>{const sec=Math.floor((Date.now()-started.current)/1000);setSeconds(sec);if(sec>=30)stop(true);},250);}catch{setError("无法使用麦克风，请在浏览器设置中允许访问后重试。");setState("error");}finally{pending.current=false;}},[stop]);
 useEffect(()=>()=>stop(false),[stop]); return {state,seconds,error,start,stop}; }

export function VoiceQuestionButton({onSubmit,position,onPause,busy=false}:{onSubmit:(blob:Blob,position:number)=>void;position:number;onPause:()=>void;busy?:boolean}){const submit=useCallback((b:Blob)=>onSubmit(b,position),[onSubmit,position]);const r=useVoiceQuestionRecorder(submit);const down=(e:React.SyntheticEvent)=>{e.preventDefault();onPause();void r.start();};const up=(e:React.SyntheticEvent)=>{e.preventDefault();r.stop(true);};const cancel=(e:React.SyntheticEvent)=>{e.preventDefault();r.stop(false);};const labels:Record<typeof r.state,string>={idle:"按住提问",recording:`正在听 · 松开发送 ${r.seconds}s`,error:"麦克风不可用 · 重试"};return <div className="voice-question-wrap"><button className={`voice-question-button ${r.state}`} disabled={busy||typeof navigator!=="undefined"&&!navigator.mediaDevices} onPointerDown={down} onPointerUp={up} onPointerCancel={cancel} onKeyDown={e=>{if((e.key===" "||e.key==="Enter")&&!e.repeat)down(e)}} onKeyUp={e=>{if(e.key===" "||e.key==="Enter")up(e)}} aria-label="按住提问">🎙 <span>{busy?"正在理解并回答":labels[r.state]}</span></button>{r.error&&<small className="voice-error">{r.error}</small>}</div>}

export function QuestionHistory({episodeId,onSeek,onPlayAnswer,refresh=0,onShowSource}:{episodeId:string;onSeek:(p:number)=>void;onPlayAnswer:(q:Question)=>void;refresh?:number;onShowSource:(ids:string[])=>void}){const [items,setItems]=useState<Question[]>([]),[loading,setLoading]=useState(true);const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(`/api/episodes/${episodeId}/questions`,{headers:{"X-Anonymous-Id":anonymousId()}});if(r.ok)setItems((await r.json()).questions||[]);}finally{setLoading(false);}},[episodeId]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load,refresh]);if(loading)return <div className="empty">正在加载提问…</div>;if(!items.length)return <div className="empty">还没有提问，按住上方按钮开始。</div>;return <div className="question-history">{items.map(q=><article className="question-card" key={q.id}><div className="question-meta">提问于 {Math.floor(q.positionSeconds/60).toString().padStart(2,"0")}:{Math.floor(q.positionSeconds%60).toString().padStart(2,"0")}</div><h3>{q.questionText}</h3>{q.answerText&&<p>{q.answerText}</p>}<div className="question-actions"><button onClick={()=>onSeek(q.positionSeconds)}>回到提问位置</button>{!!q.sourceIds?.length&&<button onClick={()=>onShowSource(q.sourceIds!)}>查看原文依据</button>}{q.answerText&&<button onClick={()=>onPlayAnswer(q)}>播放回答</button>}</div></article>)}</div>}

export function QuestionAnswerPlayer({question,onDone,onError}:{question:Question|null;onDone:()=>void;onError:(s:string)=>void}){const ref=useRef<HTMLAudioElement>(null);const [audioReady,setAudioReady]=useState(false),[audioError,setAudioError]=useState(""),[spoken,setSpoken]=useState(false),[displayed,setDisplayed]=useState("");const answer=question?.answerText||"";useEffect(()=>{setDisplayed("");if(!answer)return;let i=0;const id=window.setInterval(()=>{i++;setDisplayed(answer.slice(0,i));if(i>=answer.length)window.clearInterval(id);},45);return()=>window.clearInterval(id);},[answer]);const speak=useCallback(()=>{if(!answer||typeof window==="undefined"||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(answer);u.lang="zh-CN";u.rate=.95;u.onstart=()=>setSpoken(true);u.onend=()=>{setSpoken(false);onDone();};u.onerror=()=>setSpoken(false);window.speechSynthesis.speak(u);},[answer,onDone]);const loadAudio=useCallback(()=>{if(!question||question.status!=="ready"||!answer)return;setAudioReady(false);setAudioError("");let cancelled=false,url="";void fetch(`/api/questions/${question.id}/audio`,{method:"POST",headers:{"Content-Type":"application/json",...anonymousHeaders()},body:"{}"}).then(async r=>{if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||`回答音频生成失败（${r.status}）`);return r.blob();}).then(blob=>{if(cancelled)return;url=URL.createObjectURL(blob);setAudioReady(true);if(ref.current){ref.current.src=url;void ref.current.play().catch(()=>speak());}}).catch(()=>{if(!cancelled){setAudioError("服务端朗读不可用，已切换浏览器语音");speak();}});return()=>{cancelled=true;if(ref.current)ref.current.pause();if(url)URL.revokeObjectURL(url);};},[question,answer,speak]);useEffect(()=>loadAudio(),[loadAudio]);if(!question)return null;return <div className="answer-chat" aria-live="polite"><div className="chat-bubble user-bubble"><small>你</small><p>{question.questionText||"正在识别问题…"}</p></div>{question.status==="ready"&&answer?<div className="chat-bubble ai-bubble"><small>主持人 · AI</small><p>{displayed}<span className="typing-cursor">▌</span></p><span className="chat-hint">{spoken?"正在朗读…":audioReady?"主持人朗读中":"正在准备朗读…"}</span><button className="chat-play" onClick={()=>audioReady?void ref.current?.play():speak()}>▶ {spoken?"重新朗读":"朗读回复"}</button><audio ref={ref} onEnded={onDone} controls/></div>:question.status==="failed"?<div className="chat-bubble ai-bubble error-bubble"><small>主持人 · AI</small><p>这次回答没有生成成功，请稍后重试。</p></div>:<div className="chat-bubble ai-bubble"><small>主持人 · AI</small><p>正在理解你的问题并组织回答…</p><span className="typing-dots">● ● ●</span></div>}<button className="chat-close" onClick={onDone}>收起对话</button></div>}

export async function submitQuestion(episodeId:string,blob:Blob,position:number){const id=crypto.randomUUID();const r=await fetch(`/api/episodes/${episodeId}/questions`,{method:"POST",headers:{"Content-Type":"audio/wav","Idempotency-Key":id,"X-Playback-Position":String(position),"X-Anonymous-Id":anonymousId()},body:blob});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||"提问提交失败");return r.json();}
